opendataexplorer:
  outputs:
    dev:
      dbname: opendataexplorer
      host: opendataexplorer.aware.ro
      port: 11028
      schema: public
      threads: 1
      user: "el_user1"
      pass: "n6WFoztWL1EDN7XRVOXlLlzlFWGNv0RV6W8dyyZFR9qAAA2XbHTqz8OKh7nlBIaR3Xab8lkAOXoTDloyxpOelA9b775T"
      type: postgres
  target: dev
