version: 2

sources:
  - name: dosare_raw
    schema: public
    tags: ["dosare_raw"]
    tables:
      - name: dosare_just_ro
      - name: parti_dosare_just_ro
      - name: sedinte_dosare_just_ro
      - name: scj
      - name: scj_caiatac
      - name: scj_parti

